#!/usr/bin/env python3
"""
gen_se_key_s.py  —  Generate SECoreBin/Startup/se_key.s from key material.

The se_key.s assembly file embeds two secrets in the SE Key PCROP-protected
flash region:
  - SE_ReadKey_1      : 16-byte AES-128 symmetric key (used for FW encryption)
  - SE_ReadKey_1_Pub  : 64-byte ECC P-256 public key  (used for signature verify)

The Cortex-M7 STM instruction stores 4 registers (R1-R4) to consecutive
memory addresses in little-endian word order.  To store an arbitrary byte
sequence we convert each 4-byte group to a 32-bit little-endian word and
encode it as MOVW (lower 16 bits) / MOVT (upper 16 bits).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Encoding helpers
# ---------------------------------------------------------------------------

def _bytes_to_movw_movt_block(data16: bytes) -> list[str]:
    """Return MOVW/MOVT/STM assembly lines for a 16-byte block into R1-R4."""
    assert len(data16) == 16, f"Expected 16 bytes, got {len(data16)}"
    lines: list[str] = []
    for i in range(4):
        word = int.from_bytes(data16[i * 4 : i * 4 + 4], "little")
        lo = word & 0xFFFF
        hi = (word >> 16) & 0xFFFF
        reg = f"R{i + 1}"
        lines.append(f"\tMOVW {reg}, #0x{lo:04x}")
        lines.append(f"\tMOVT {reg}, #0x{hi:04x}")
    lines.append("\tSTM R0, {R1-R4}")
    return lines


def generate_se_key_s(aes_key: bytes, pub_key_x: bytes, pub_key_y: bytes) -> str:
    """
    Build the full se_key.s text.

    Parameters
    ----------
    aes_key   : 16 bytes — AES-128 symmetric key (raw)
    pub_key_x : 32 bytes — P-256 public key X coordinate (big-endian)
    pub_key_y : 32 bytes — P-256 public key Y coordinate (big-endian)

    Returns
    -------
    str — contents of se_key.s
    """
    if len(aes_key) != 16:
        raise ValueError(f"AES key must be 16 bytes, got {len(aes_key)}")
    if len(pub_key_x) != 32:
        raise ValueError(f"pub_key_x must be 32 bytes, got {len(pub_key_x)}")
    if len(pub_key_y) != 32:
        raise ValueError(f"pub_key_y must be 32 bytes, got {len(pub_key_y)}")

    pub_key = pub_key_x + pub_key_y  # 64 bytes total

    lines: list[str] = []
    lines += [
        "/**",
        "  ******************************************************************************",
        "  * @file      se_key.s",
        "  * @brief     ReadKey from PCROP area - generated by gen_se_key_s.py",
        "  *            DO NOT EDIT MANUALLY.  Re-run generate_keys.py to refresh.",
        "  ******************************************************************************",
        "  */",
        "",
        "\t.section .SE_Key_Data,\"ax\",%progbits",
        "\t.syntax unified",
        "\t.thumb",
        "\t.global SE_ReadKey_1",
    ]

    # -----------------------------------------------------------------------
    # SE_ReadKey_1 — AES-128 symmetric key (16 bytes)
    # -----------------------------------------------------------------------
    lines.append("\t.thumb_func")   # mark as a Thumb function (required for BL relocs)
    lines.append("SE_ReadKey_1:")
    lines.append("\tPUSH {R1-R5}")
    lines += _bytes_to_movw_movt_block(aes_key)
    lines += [
        "\tPOP {R1-R5}",
        "\tBX LR",
        "",
    ]

    # -----------------------------------------------------------------------
    # SE_ReadKey_1_Pub — ECC P-256 public key (64 bytes in 4 x 16-byte blocks)
    # -----------------------------------------------------------------------
    lines.append("\t.global SE_ReadKey_1_Pub")
    lines.append("\t.thumb_func")   # mark as a Thumb function (required for BL relocs)
    lines.append("SE_ReadKey_1_Pub:")
    lines.append("\tPUSH {R1-R5}")

    for block_idx in range(4):
        chunk = pub_key[block_idx * 16 : block_idx * 16 + 16]
        lines += _bytes_to_movw_movt_block(chunk)
        if block_idx < 3:
            lines.append("\tADD R0, R0, #16")

    lines += [
        "\tPOP {R1-R5}",
        "\tBX LR",
        "",
        "\t.end",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate se_key.s from AES and ECC key files."
    )
    parser.add_argument(
        "--aes-key", required=True,
        help="Path to the 16-byte raw AES-128 key file (binary).",
    )
    parser.add_argument(
        "--pub-key-x", required=True,
        help="Path to the 32-byte raw P-256 X coordinate (big-endian binary).",
    )
    parser.add_argument(
        "--pub-key-y", required=True,
        help="Path to the 32-byte raw P-256 Y coordinate (big-endian binary).",
    )
    parser.add_argument(
        "--output",
        default=str(
            Path(__file__).resolve().parent.parent
            / "SECoreBin" / "Startup" / "se_key.s"
        ),
        help="Output path for se_key.s (default: SECoreBin/Startup/se_key.s).",
    )
    args = parser.parse_args()

    aes_key  = Path(args.aes_key).read_bytes()
    pub_x    = Path(args.pub_key_x).read_bytes()
    pub_y    = Path(args.pub_key_y).read_bytes()

    content = generate_se_key_s(aes_key, pub_x, pub_y)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="ascii")

    print(f"[gen_se_key_s] Written: {out_path}")


if __name__ == "__main__":
    main()
